# Generated by Django 4.2.9 on 2026-03-18 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_topicperformance',
            },
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quizzes_taken', models.PositiveIntegerField(default=0)),
                ('total_quizzes_created', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_score', models.FloatField(default=0.0)),
                ('total_time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('strongest_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('weakest_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_userstat',
            },
        ),
    ]
