# Generated by Django 4.2.9 on 2026-03-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='topicperformance',
            index=models.Index(fields=['user', 'topic'], name='analytics_t_user_id_163deb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicperformance',
            unique_together={('user', 'topic')},
        ),
    ]
