# Generated by Django 4.2.9 on 2026-03-19 05:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('lowest_score', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'analytics_quizstat',
            },
        ),
    ]
