# Generated by Django 4.2.9 on 2026-03-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status'], name='quizzes_qui_status_376889_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_public'], name='quizzes_qui_is_publ_df0430_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['topic'], name='quizzes_qui_topic_7203f1_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_by', 'created_at'], name='quizzes_qui_created_5e4983_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quizzes_que_quiz_id_904735_idx'),
        ),
    ]
