# Generated by Django 4.2.9 on 2026-03-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='quizzes.choice'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz'),
        ),
    ]
